
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author crn70
 */
public class gui extends javax.swing.JFrame {
    int numeroSecreto;
private int intento = 0;
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        
        //Generar número random.

        Random random = new Random();
        numeroSecreto = random.nextInt(900) + 100;
        int pass1 = numeroSecreto / 100;
        int pass2 = (numeroSecreto / 10) % 10;
        int pass3 = numeroSecreto % 10;
        passRevelar1.setText(String.valueOf(pass1));
        passRevelar2.setText(String.valueOf(pass2));
        passRevelar3.setText(String.valueOf(pass3));

        //Ocultar el número secreto con "$".
        passRevelar1.setEchoChar('$');
        passRevelar2.setEchoChar('$');
        passRevelar3.setEchoChar('$');

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        passRevelar1 = new javax.swing.JPasswordField();
        passRevelar2 = new javax.swing.JPasswordField();
        passRevelar3 = new javax.swing.JPasswordField();
        lblPista = new javax.swing.JLabel();
        btnRevelarNumero = new javax.swing.JButton();
        lblTrofeo = new javax.swing.JLabel();
        lblCodigoSecreto = new javax.swing.JLabel();
        txtCodigoEscribir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passRevelar1.setEditable(false);
        passRevelar1.setBackground(new java.awt.Color(204, 153, 255));
        passRevelar1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        passRevelar1.setText("$");
        passRevelar1.setToolTipText("");
        passRevelar1.setActionCommand("<Not Set>");
        passRevelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passRevelar1.setFocusable(false);
        passRevelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passRevelar1ActionPerformed(evt);
            }
        });

        passRevelar2.setEditable(false);
        passRevelar2.setBackground(new java.awt.Color(255, 255, 153));
        passRevelar2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        passRevelar2.setText("$");
        passRevelar2.setFocusable(false);
        passRevelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passRevelar2ActionPerformed(evt);
            }
        });

        passRevelar3.setEditable(false);
        passRevelar3.setBackground(new java.awt.Color(153, 255, 153));
        passRevelar3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        passRevelar3.setText("$");
        passRevelar3.setFocusable(false);
        passRevelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passRevelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(passRevelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(passRevelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(passRevelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passRevelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passRevelar1)
                    .addComponent(passRevelar3))
                .addContainerGap())
        );

        lblPista.setForeground(new java.awt.Color(255, 255, 51));
        lblPista.setText("                                                                         Por favor, Ingresa exactamente 3 numeros.");
        lblPista.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        btnRevelarNumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-formato-claro-48.png"))); // NOI18N
        btnRevelarNumero.setText("Revelar");
        btnRevelarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevelarNumeroActionPerformed(evt);
            }
        });

        lblTrofeo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCodigoSecreto.setFont(new java.awt.Font("Cambria Math", 2, 24)); // NOI18N
        lblCodigoSecreto.setForeground(new java.awt.Color(255, 255, 0));
        lblCodigoSecreto.setText("Codigo Secreto");

        txtCodigoEscribir.setBackground(new java.awt.Color(255, 204, 204));
        txtCodigoEscribir.setForeground(new java.awt.Color(255, 102, 102));
        txtCodigoEscribir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "escribe 3 digitos + ENTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 2, 18), new java.awt.Color(255, 51, 51))); // NOI18N
        txtCodigoEscribir.setCaretColor(new java.awt.Color(255, 102, 102));
        txtCodigoEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoEscribirActionPerformed(evt);
            }
        });
        txtCodigoEscribir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoEscribirKeyTyped(evt);
            }
        });

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblPista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRevelarNumero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblTrofeo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblCodigoSecreto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtCodigoEscribir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblPista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(155, 155, 155)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCodigoSecreto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 52, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCodigoEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRevelarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblCodigoSecreto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRevelarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblPista, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(0, 51, Short.MAX_VALUE)
                                .addComponent(txtCodigoEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTrofeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passRevelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passRevelar1ActionPerformed
        // TODO add your handling code here:
        

      
        
        
    }//GEN-LAST:event_passRevelar1ActionPerformed

    private void passRevelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passRevelar2ActionPerformed







        // TODO add your handling code here:
    }//GEN-LAST:event_passRevelar2ActionPerformed

    private void passRevelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passRevelar3ActionPerformed


 




        // TODO add your handling code here:
    }//GEN-LAST:event_passRevelar3ActionPerformed

    private void btnRevelarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevelarNumeroActionPerformed
        

  if (intento == 0) {
        
        passRevelar1.setEchoChar((char)0);
        JOptionPane.showMessageDialog(rootPane, "primer número revelado");
        intento++;
        
    } else if (intento == 1) {
        
        passRevelar2.setEchoChar((char)0);
        JOptionPane.showMessageDialog(rootPane, "segundo número revelado");
        intento++;
        
        
        /*
    } else if (intento == 2) {
        
        passRevelar3.setEchoChar((char)0);
        JOptionPane.showMessageDialog(rootPane, "tercer número revelado");
        intento+=3;
        
        esto es por si necesitamos revelar todos los numeros haciendo otro if else con el mismo metodo :d
        
        */ 
        
        
    } else {
        
        JOptionPane.showMessageDialog(rootPane, "ya no hay más intentos");
    }
               
            
          

        
      









        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevelarNumeroActionPerformed

	private void txtCodigoEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoEscribirActionPerformed
    // TODO add your handling code here:
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    int CodigoSecreto1;
    
    CodigoSecreto1 = numeroSecreto;
    String ingreso = txtCodigoEscribir.getText();

    int numeroIngresado = Integer.parseInt(ingreso);

    if (numeroIngresado == numeroSecreto) {
        passRevelar1.setEchoChar((char)0);
        passRevelar2.setEchoChar((char)0);
        passRevelar3.setEchoChar((char)0);
        lblPista.setText("el código es correcto");
        
     try{
         java.net.URL url = new java.net.URL("https://images.vexels.com/media/users/3/202189/isolated/lists/4f3a5cb84297726d74d69dce22676f83-trofeo-numero-1-plano.png");
        javax.swing.ImageIcon icon= new javax.swing.ImageIcon(url);
        java.awt.Image img = icon.getImage().getScaledInstance(120, 120, java.awt.Image.SCALE_SMOOTH);
        lblTrofeo.setIcon(new javax.swing.ImageIcon(img));
        lblTrofeo.setText("");         
     }catch(Exception e){
         System.out.println("Imagen de victoria");
     }
        
    } else if (numeroIngresado < numeroSecreto) {
        lblPista.setText("el código secreto es mayor");
    } else {
        lblPista.setText("el código secreto es menor");
    }
        
        
        
        
        
        
    
	}//GEN-LAST:event_txtCodigoEscribirActionPerformed

    private void txtCodigoEscribirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEscribirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoEscribirKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new gui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevelarNumero;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoSecreto;
    private javax.swing.JLabel lblPista;
    private javax.swing.JLabel lblTrofeo;
    private javax.swing.JPasswordField passRevelar1;
    private javax.swing.JPasswordField passRevelar2;
    private javax.swing.JPasswordField passRevelar3;
    private javax.swing.JTextField txtCodigoEscribir;
    // End of variables declaration//GEN-END:variables
}